version: "3.7" # Версия Docker Compose файла
services: # Описание микросервисов (контейнеров)
  regression: # Имя контейнера (по умолчанию добавится -1)
    image: chrome:v2 # Базовый образ для контейнера (если такого нет, соберется из докерфайла)
    build: # Инструкции для сборки образа, если он не найден
      context: . # Контекст сборки (текущая директория)
      dockerfile: Dockerfile # Имя Dockerfile
    volumes: # Тома для монтирования
      - ./:/app #  Папка на виртуалке
    command: /bin/sh -c "pytest -sv -o log_cli=true --alluredir=report" # Команда для выполнения в контейнере

    tty: true # Для цветного вывода логов